#!/bin/bash

for dir in */; do
  if ls $dir*.cc >/dev/null 2>&1; then 
    clang-format -style=Google -i $dir*.cc
  fi

  if ls $dir*.h >/dev/null 2>&1; then
    clang-format -style=Google -i $dir*.h
  fi
done
